### ISSUE TITLE
修复：PHP Version 7.4 下 Deprecated/Notice错误

### ISSUE THREAD

**Issue by peacexie** [baagee/qr-code-reader#4]
### 错误信息：

* Deprecated: Array and string offset access syntax with curly braces is deprecated 
in E:\webs\jobn\qr-code-reader-master\lib\common\BitMatrix.php on line 37

* Notice: Trying to get property '2' of non-object 
in E:\webs\jobn\qr-code-reader-master\lib\common\BitMatrix.php on line 38

### 出错文件：

* \lib\qrcode\decoder\DecodedBitStreamParser.php
* \lib\common\BitMatrix.php
* Files as these:[qr-code-reader-fix.zip](https://github.com/baagee/qr-code-reader/files/4398463/qr-code-reader-fix.zip)

**Comment by baagee** [comment]
> ### 错误信息：
> * Deprecated: Array and string offset access syntax with curly braces is deprecated
>   in E:\webs\jobn\qr-code-reader-master\lib\common\BitMatrix.php on line 37
> * Notice: Trying to get property '2' of non-object
>   in E:\webs\jobn\qr-code-reader-master\lib\common\BitMatrix.php on line 38
> 
> ### 出错文件：
> * \lib\qrcode\decoder\DecodedBitStreamParser.php
> * \lib\common\BitMatrix.php
> * Files as these:[qr-code-reader-fix.zip](https://github.com/baagee/qr-code-reader/files/4398463/qr-code-reader-fix.zip)

嗯，我已经改了。

**Comment by peacexie** [comment]
1. 用你最新的代码，还是出现很多如下提示（PHP7.4）

Deprecated: Array and string offset access syntax with curly braces is deprecated 
in ...\QrReader\qrcode\decoder\DecodedBitStreamParser.php on line 285

2. 你用PHP7.3 / PHP7.4测试一下看看？
提示：类似代码如下修改：
$result{$i} -=> substr($result,$i,1)

**Comment by baagee** [comment]
> 1. 用你最新的代码，还是出现很多如下提示（PHP7.4）
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated
> in ...\QrReader\qrcode\decoder\DecodedBitStreamParser.php on line 285
> 
> 1. 你用PHP7.3 / PHP7.4测试一下看看？
>    提示：类似代码如下修改：
>    $result{$i} -=> substr($result,$i,1)



> 1. 用你最新的代码，还是出现很多如下提示（PHP7.4）
> 
> Deprecated: Array and string offset access syntax with curly braces is deprecated
> in ...\QrReader\qrcode\decoder\DecodedBitStreamParser.php on line 285
> 
> 1. 你用PHP7.3 / PHP7.4测试一下看看？
>    提示：类似代码如下修改：
>    $result{$i} -=> substr($result,$i,1)

修改了
